#+TITLE: Ryan's ~dwm~ config
#+AUTHOR: Ryan
#+EMAIL: rmjxyz@gmail.com
#+OPTIONS: num:nil

Here is my ~dwm~ build optimzed for Emacs.

It is a [[https://github.com/LukeSmithxyz/dwm][fork of Luke Smith's dwm config]] so all of his patches (up to the version that was forked) and other details also apply, except for the keybindings.

* Installation
#+BEGIN_SRC shell
chmod +x setup
./setup && make && sudo make install && make clean
#+END_SRC

This fork also puts a dwm.desktop file in ~/usr/share/xsessions/~
so a desktop manager such as ~lightdm~ will be able to boot into ~dwm~.

This fork also installs the bar customizations script, which is also placed in ~/usr/share/xsessions/~.
It relies on the scripts ~dwmbar.sh~ and ~ryansleep.sh~ which it assumes is in ~$HOME/src/dwm/~.
** Customization
The ~dwminit.sh~ file assumes ~compton~ as the compositing window manager, you might want to change this.

You should set your wallpaper, also in dwminit.sh.

* Remember to install [[https://aur.archlinux.org/packages/libxft-bgra/][libxft-bgra]]
...unless you want ~dwm~ to crash every time it encounters an emoji.

* How the bar works
~dwm~'s default bar is updated by running ~xsetroot -name "string"~. The update script refreshes the bar
every 20 seconds (or however many seconds is in ~ryansleep.sh~). When a time sensitive action occurs, it
kills the ~ryansleep.sh~ process, allowing the bar to update instantly.
